AddOnAgg: false
Aggregate: false
AttnMaps: false
EGAT_layers: 4
Embed: false
Norm: false
Residual: null
SA: false
UMAP: false
UMAP_model: null
additionals: DH
atom_map: false
base_model: null
batch_size: 50
betas:
- 0.9
- 0.999
class_choice: null
cpus: 10
data_path: null
days: '00'
defaults:
  model: EGAT_3MLP_1OUT
destination: null
dist: 0.1
drop_list: false
epoch: 30
epoch_const: 10
epsilon: 1.0e-08
exclude: exclude.txt
exp_decay: 5
fold: null
folders: Molecularity
foldtype: null
getbondpolarity: false
getbondrot: false
getbridgehead: false
geteneg: false
gethbinfo: false
getradical: null
getspiro: false
gpu: 1
hasaddons: false
hasnormedaddons: false
hours: '23'
hydra:
  run:
    dir: log/direct/None
  sweep:
    dir: log/direct
    subdir: null
input: sample.csv
learning_rate: 1.0e-05
lr_decay: 0.6
lr_min: 2.0e-05
method_mapping: null
metric: euclidian
minutes: '50'
model: null
model_type: direct
molecular: false
momentum: 0.9
momentum_orig: 0.1
n_components: 1
n_neighbors: 32
nodes: 1
npoints: 33
num_workers: 1
onlyH: false
optimizer: Adam
output: EGAT.yaml
partition: standby
patience: 2
pred_loss: null
purpose: Train
randomize: false
removearomaticity: false
removebondorderinfo: false
removebondtypeinfo: false
removechiralinfo: false
removeconjinfo: false
removeelementinfo: false
removeformalchargeinfo: false
removehybridinfo: false
removereactiveinfo: false
removeringinfo: false
removestereoinfo: false
save_path: null
scheduler: 2
shuffle: false
size: null
smiles: smiles
split: null
startpoint: null
step_size: 20
target: DE
test_only: false
train_loss: MAE
tweights:
- 0.5
- 0.5
umap_input: null
umap_outfile: null
user: null
wandbproject: null
wandbrun: null
warmup: 2
weight_decay: 0.0001
weightsandbiases: false
